DROP TABLE IF EXISTS EMPLOYEE ;
DROP TABLE IF EXISTS DEPARTMENT ;
DROP TABLE IF EXISTS MANAGER ;
DROP TABLE IF EXISTS PROJECTS ;

Create table Employee
(
emp_id varchar(20) PRIMARY KEY,
emp_name varchar(50),
salary int,
dept_id  varchar(20),
manager_id  varchar(20)
) ;

INSERT INTO EMPLOYEE (emp_id,emp_name,salary,dept_id,manager_id)
VALUES
      ('E1','Rahul','15000','D1','M1'),
	  ('E2','Manoj','15000','D1','M1'),
	  ('E3','James','55000','D2','M2'),
	  ('E4','Michael','25000','D2','M2'),
	  ('E5','Ali','20000','D10','M3'),
	  ('E6','Robin','35000','D10','M3');

Create table Department
(
dept_id varchar(20) PRIMARY KEY,
dept_name varchar(50)
);

INSERT INTO DEPARTMENT (dept_id,dept_name)
VALUES
      ('D1','IT'),
	  ('D2','HR'),
	  ('D3','FINANCE'),
	  ('D4','ADMIN');
	  

Create table Manager
(
manager_id varchar(20) PRIMARY KEY,
manager_name varchar(50),
dept_id  varchar(20)
);

INSERT INTO MANAGER (manager_id,manager_name,dept_id)
VALUES
      ('M1','Prem','D3'),
	  ('M2','Shripadh','D4'),
	  ('M3','Nick','D1'),
	  ('M4','Cory','D1');

Create table Projects
(
project_id varchar(20),
project_name varchar(100),
team_member_id varchar(20)
);

INSERT INTO PROJECTS (project_id,project_name,team_member_id)
VALUES
      ('P1','Data Migration','E1'),
	  ('P1','Data Migration','E2'),
	  ('P1','Data Migration','M3'),
	  ('P2','ETL Tool','E1'),
	  ('P2','ETL Tool','M4');

Select * from employee ;
Select * from department ;
Select * from manager ;
Select * from projects ;

--- INNER JOIN / JOIN

--- fetch the employee name and the department name they belong to.
--- When joining the column name doest not matter they values have to match that is important


SELECT EMP_NAME,DEPT_NAME
FROM EMPLOYEE
INNER JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

---- fetch the details of all the employee name and their department name

---- LEFT JOIN WILL DO AN INNER JOIN FIRST AND THE ADDITIONALLY IT WILL CHECK FOR ADDITIONAL RECORD FROM LEFT JOIN THAT WERE NOT INCLUDED IN THE INNER JOIN

--- BY LEFT AND RIGHT IT MEANS THAT THE TABLE MENTIONED ON THE LEFT OF THE JOIN KEYWORD AND RIGHT OF THE JOIN KEYWORD

--- LEFT JOIN OR LEFT OUTER JOIN

SELECT EMP_NAME,DEPT_NAME
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

--- RIGHT JOIN OR RIGHT OUTER JOIN

SELECT EMP_NAME,DEPT_NAME
FROM EMPLOYEE
RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

--- WRITE A QUERY TO FETCH DETAILS OF ALL EMPLOYEES THEIR MANAGER THEIR DEPARTMENT AND THE PROJECTS THEY WORK ON
--- WE HAVE TO USE ALL TABLES SO WE HAVE TO JOIN ALL OF THEM

--- YOU HAVE TO KEEP THE PRIMARY TABLE AS THE TABLE FROM WHICH YOU NEED ALL RECORDS

SELECT E.EMP_NAME,D.DEPT_NAME,M.MANAGER_NAME,P.PROJECT_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
INNER JOIN MANAGER M ON E.MANAGER_ID = M.MANAGER_ID
LEFT JOIN PROJECTS P ON E.EMP_ID = P.TEAM_MEMBER_ID;

------ THE LAST LEFT JOIN IN THE ABOVE QUERY CONSIDERS THE OUTPUT OF ALL QUERIES ABOVE IT THAT IS ALL THE JOINS NOT ONLY THE IMMEDIATE JON ABOVE IT 

--- FULL OUTER JOIN/ FULL JOIN
--- FIRST DOES INNER JOIN FIRST, THEN LOOKS INTO LEFT TABLE FETCHES THE ONES LEFT OUT FROM INNER JOIN
--- THEN FETCHES THE LEFT ONES FROM RIGHT TABLE

SELECT EMP_NAME,DEPT_NAME
FROM EMPLOYEE
FULL JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;


--- CROSS JOIN OR CARTESIAN JOIN
--- EVERY RECORD IN THE LEFT TABLE IS MACTHED WITH EVERY RECORD IN THE RIGHT TABLE

DROP TABLE IF EXISTS COMPANY;

CREATE TABLE COMPANY 
(
COMPANY_ID VARCHAR(10),
COMPANY_NAME VARCHAR(50),
LOCATION VARCHAR(20)
);

INSERT INTO COMPANY (COMPANY_ID,COMPANY_NAME,LOCATION)
VALUES ('C001','TECHTFQ SOLUTIONS','KUALA LUMPUR');

SELECT* FROM COMPANY;

SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE E -- 6 RECORDS
CROSS JOIN DEPARTMENT D;  -- 4 RECORDS (6*4=24 IS RETURNED)

--- PLACES WHERE CROSS JOIN IS USE
--- WRITE A QUERY TO FETCH THE EMPLOYEE NAME AND THEIR CORRESPONDING DEPARTMENT NAME
--- ALSO MAKE SURE TO DISPLAY THE COMPANY NAME AND THE COMPANY LOCATION CORRESPONDING TO EACH EMPLOYEE
--- HERE YOU HAVE TO CONNECT EVERY EOMPLOYEE TO THE SAME COMPANY HERE 

--- WHEN YOU DONT HAVE COMMON COLUMNS TO USE A JOIN AND STILL NEED TO 
--FETCH DATA FROM A TABLE CROSS JOIN IS USEFUL

SELECT EMP_NAME,DEPT_NAME,COMPANY_NAME,LOCATION
FROM EMPLOYEE
INNER JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID
CROSS JOIN COMPANY ;


--WE DO NOT NEED TO USE ON CLAUSE IN CROSS AND NATURAL JOIN 

--- NATURAL JOIN - IT IS NOT EXACTLY A INNER JOIN IT IS DIFFERENT 
--AND IT IS NOT PREFERABLE.HERE SQL DECIDES ON WHICH COLUMN THE JOIN SHOULD HAPPEN
-- SQL CHECKS FOR MATCHING COLUMN AND RETURNS IT

SELECT * FROM EMPLOYEE E
NATURAL JOIN DEPARTMENT D;  -- THIS OUTPUT LOOKS LIKE INNER JOIN O/P BUT IT IS NOT THE SAME

--- FOR EXAMPLE WHEN THERE IS MATCHING COLUMN NAME BUT THE 
---VALUE STORED IN THE COLUMNS ARE DIFFERENT , NATURAL JOIN CAN GO WRONG

ALTER TABLE DEPARTMENT RENAME COLUMN DEPT_ID TO ID;

SELECT * FROM EMPLOYEE E
NATURAL JOIN DEPARTMENT D;  ---NOW THIS GIVES A DIFFERENT OUTPUT AS THE COLUMN NAMES DID NOT MATCH
                            -- SO SQL HAS DONE A CROSS JOIN

--- IF THERE ARE INCASE MORE THAN TWO COLUMNS WITH SAME NAME THEN NATURAL JOIN WILL JOIN ALL THE MATCHING COLUMNS


ALTER TABLE DEPARTMENT RENAME ID TO DEPT_ID;


--- SELF JOIN
--- JOINING A TABLE TO ITSELF

DROP TABLE IF EXISTS FAMILY;

CREATE TABLE FAMILY 
(
MEMBER_ID VARCHAR(10),
NAME VARCHAR(50),
AGE INT,
PARENT_ID VARCHAR(50)
) ;

INSERT INTO FAMILY(MEMBER_ID,NAME,AGE,PARENT_ID)
VALUES
      ('F1','DAVID',4,'F5'),
	  ('F2','CAROL',10,'F5'),
      ('F3','MICHAEL',12,'F5'),
      ('F4','JOHNSON',36,''),
      ('F5','MARYAM',40,'F6'),
      ('F6','STEWART',70,''),
      ('F7','ROHAN',6,'F4'),
	  ('F8','ASHA',8,'F4');

SELECT * FROM FAMILY;

--- HERE WE DONT HAVE TWO TABLE LIKE ONE FOR PARENT AND ONE FOR CHILDERN
--- BUT I WANT TO KNOW WHO IS WHOSE PARENT JUST WITH DETAILS FROM ONE TABLE

--- WHEN YOU WANT TO MATCH ONE RECORD OF THE TABLE TO ANOTHER RECORD OF THE SAME TABLE USE SELF JOIN

--- GIVING PROPER ALIAS IS IMPORTANT
--- THERE IS NO KEY WORD FOR SELF JOIN , YOU CAN USE ANY JOIN TYPE 

SELECT CHILD.NAME AS CHILD_NAME, CHILD.AGE AS CHILD_AGE,
       PARENT.NAME AS PARENT_NAME, PARENT.AGE AS PARENT_AGE
FROM FAMILY AS CHILD
JOIN FAMILY AS PARENT ON 
CHILD.PARENT_ID = PARENT.MEMBER_ID ;


SELECT CHILD.NAME AS CHILD_NAME, CHILD.AGE AS CHILD_AGE,
       PARENT.NAME AS PARENT_NAME, PARENT.AGE AS PARENT_AGE
FROM FAMILY AS CHILD
LEFT JOIN FAMILY AS PARENT ON 
CHILD.PARENT_ID = PARENT.MEMBER_ID ;

SELECT CHILD.NAME AS CHILD_NAME, CHILD.AGE AS CHILD_AGE,
       PARENT.NAME AS PARENT_NAME, PARENT.AGE AS PARENT_AGE
FROM FAMILY AS CHILD
RIGHT JOIN FAMILY AS PARENT ON 
CHILD.PARENT_ID = PARENT.MEMBER_ID ;


