CREATE DATABASE SCORE;
USE SCORE;
CREATE TABLE STUDENT(NUM INT, NAME VARCHAR(15), MARKS FLOAT);
ALTER TABLE STUDENT ADD COLUMN DEPARTMENT VARCHAR(50);
DESCRIBE STUDENT;
INSERT INTO STUDENT VALUES 
( 1, "KIRTHIKA", 100 , "EEE"), 
(2, "MONIKA", 83.56 , "CSE"), 
(3, "JANET", 75.8 , "IT"), 
(4, "ABEL", 96.5 , "MECHANICAL");
SELECT* FROM STUDENT;
SELECT NUM,NAME FROM STUDENT;
